from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from nova_generator.domain.jobs import Job


class JobRepository(Protocol):
    def enqueue(
        self, *, kind: str, input: dict[str, Any], idempotency_key: str | None, max_attempts: int
    ) -> Job: ...
    def claim_next(self, *, worker_id: str, now: datetime) -> Job | None: ...
    def heartbeat(self, *, job_id: str, worker_id: str, now: datetime) -> bool: ...
    def cancellation_requested(self, *, job_id: str, worker_id: str) -> bool: ...
    def request_cancellation(self, *, job_id: str, now: datetime) -> Job | None: ...
    def succeed(
        self, *, job_id: str, worker_id: str, output: dict[str, Any], now: datetime
    ) -> bool: ...
    def fail(self, *, job_id: str, worker_id: str, error_message: str, now: datetime) -> bool: ...
    def cancel(self, *, job_id: str, worker_id: str, now: datetime) -> bool: ...
    def recover_abandoned(self, *, before: datetime, now: datetime) -> int: ...
    def get(self, job_id: str) -> Job | None: ...
    def list(
        self, *, offset: int, limit: int, status: str | None = None
    ) -> tuple[list[Job], int]: ...
    def retry(self, *, job_id: str, now: datetime) -> Job | None: ...
    def latest_status_for_project(self, project_id: str) -> str | None: ...
    def latest_for_project(
        self, project_id: str, kind: str, status: str | None = None
    ) -> Job | None: ...
